### ISSUE TITLE
Оценка с точки зрения пользователя

### ISSUE THREAD

**Issue by steindvart** [zCRUSADERz/Minesweeper#1]
1. Надо установить ограничения в верхнем диапазоне выбора ширины поля а то получается, что я сейчас создал поле в ширину 1000 ячеек, что окно вышло далеко за переделы экрана и вообще перестало работать при нажатии на ячейки, хотя таймер идёт.
![unknown](https://user-images.githubusercontent.com/53004350/63571718-36253b80-c5ab-11e9-8a65-6a9fbd331b20.png)

2. При параметрах: ширина 9, высота 1, кол-во мин 1: 
что-то натыкал и программа зациклилась, загрузив процессор на 100%.
![unknown](https://user-images.githubusercontent.com/53004350/63571819-869c9900-c5ab-11e9-9f0e-73ded7708a58.png)

**Comment by zCRUSADERz** [comment]
@Kalashnikov-Ivan благодарю вас за отзыв. 

Проблема №2 с зависанием с такими параметрами игрового поля была решена в ff6913f2eef9dd4bec131af9afcb0f895d73d091. Релиз [0.1.1 ](https://github.com/zCRUSADERz/Minesweeper/releases/tag/0.1.1) не содержит данного бага.

P.S. На будущее, каждую проблему нужно оформлять в отдельных issues.
